(******************************************************************************)
(*                                                                            *)
(*                  Bell Staging for Necrotizing Enterocolitis                *)
(*                                                                            *)
(*     Formalization of modified Bell staging criteria for NEC in neonates:   *)
(*     Stage I (suspected), Stage II (definite), Stage III (advanced).        *)
(*     Clinical signs, radiographic findings, and systemic manifestations.    *)
(*     Decision predicates for staging and surgical intervention triggers.    *)
(*                                                                            *)
(*     "I will stand at my watch and station myself on the ramparts; I will   *)
(*     look to see what he will say to me."                                   *)
(*     - Habakkuk 2:1                                                         *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 6, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
